artifacts_roots: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL: https://github.com/julianlebouc/SPAM_MAIL_DETECTION/blob/main/artifacts/data_ingestion/data_mails.zip
  local_data_file : artifacts/data_ingestion/data_mails.zip
  unzip_dir : artifacts/data_ingestion/

data_validation:
  root_dir : artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/data_mails/
  STATUS_FILE : artifacts/data_validation/status.txt


data_transformation:
  root_dir : artifacts/data_transformation
  unzip_data_dir : artifacts/data_ingestion/data_mails/


model_trainer:
  root_dir : artifacts/model_trainer
  train_data_path: artifacts/data_transformation/data.pkl
  test_data_path: artifacts/data_transformation/classes.csv
  model_name: model.joblib



model_evaluation:
  root_dir : artifacts/model_evaluation
  train_data_path: artifacts/data_transformation/data.pkl
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

